### ISSUE TITLE
Warp doesn't slow or stop while landing, causing ship to crash!

### ISSUE THREAD

**Issue by Rethkir** [ntwest/TimeControl#35] opened 2017-12-27 03:38 UTC
In stock KSP, I can warp as fast as I want while making a descent towards a celestial body with full confidence that the game will slow and stop warping in time so I can safely make my descent burn before I land. However, when I have this mod installed, the game will no longer pull me out of warp while heading towards the celestial body, which ends up causing my ship and all the poor Kerbals on board end in a firey fate.

This issue can be reproduced every time I make a landing attempt and occurs whether or not I have modified the rail warp altitudes or multipliers. The only way to provent this from happening is to uninstall the mod entirely. I want to use this mod, but not being able to safely control landings is a complete dealbreaker for me. Please fix this issue.

Thanks.

**Comment by ntwest** [comment] 2018-01-10 02:47
I could swear I have not had this problem, but I will attempt to reproduce and let you know.

**Comment by ntwest** [comment] 2018-01-10 03:00
I cannot reproduce the issue on a clean install of KSP 1.3.1 with only TimeControl and Kerbal Alarm Clock installed. Just tried to land on the mun, the warp slows down at the appropriate altitudes around the Mun . There are cases when this can happen on the Mun and other celestial bodies if you are landing on a high altitude spot. The altitude that KSP uses to slow down warp is 'sea level' - not height of the terrain (which is what the altimeter shows). Can you please share your log file - maybe there is a mod or version conflict? You can post it to the KSP forum or here.

**Comment by ntwest** [comment] 2018-03-15 00:29
No updates, closing.

**Closed as completed by ntwest** 2018-03-15 00:29 UTC
Labels: more info needed
